server:
  env: "local"
  http:
    port: 8080

url_shortener:
  base_url: "http://localhost:8080/"
  black_list:
    domains:
      - "naughtyamerica.com"
      - "pornhub.org"
      - "ok.xxx"

cors:
  enabled: true
  origin: "*" #specific origins when needed
  methods: "GET,POST,PUT,DELETE"
  headers: ["Content-Type", "Authorization"]
  credentials: true

redis:
  host: "localhost"
  port: 6379

mongodb:
  host: "localhost"
  port: 27017
  database: "urlShortener"