version: "3.3"

services:
  backend:
    build: .
    container_name: node-express-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=local
    volumes:
      - .:/app
      - /app/node_modules  # prevents overwriting of node modules
    command: ["npm", "run", "start"]  
    restart: always
  
  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  mongo:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: always 

volumes:
  redis_data:
  mongo_data: